modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (28 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="examplemod" #mandatory
version="1.0.0" #mandatory
displayName="Example Mod" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
Example World Gen
'''

[[dependencies.examplemod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"